plugins {
    id 'com.android.application'
}

android {
    namespace 'kr.knto.dtid.widget'
    compileSdk 34

    defaultConfig {
        applicationId "kr.knto.dtid.widget"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.zxing:core:3.5.3'
}
